accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/mypage/', views.mypage, name='mypage'),

    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/comment/create', views.comment_create, name='comment_create'),
    path('<int:article_id>/comment/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),

    path('search/', views.search, name='search'),
    path('<int:id>/like/', views.like, name='like'),
]

dcinside/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dcinside/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>gallery.com</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Bangers&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:700&display=swap" rel="stylesheet">
  <link rel="icon" href="{% static 'icon.png' %}">
  <style>
    #title{
      font-family: 'Bangers', cursive;
    }
    #content{
      position: relative
    }
    aside {
      position: absolute;
      top: 100px;
    }
    #name{
      font-family: 'Nanum Gothic', sans-serif;
    }
  </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg" style="background-color:#4a57a8;">
      <a id="title" class="navbar-brand text-white" href="{% url 'articles:index' %}">gallery. com</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <form class="form-inline my-2 my-lg-0" action="{% url 'articles:search' %}">
            <input class="form-control" type="search" name="keyword" placeholder="통합 검색">
            <button class="btn btn-outline-white my-2 my-sm-0" type="submit"><i class="fas fa-search" style="color: white;"></i></button>
          </form>
        </ul>

        <ul class="navbar-nav mr-5 pr-5">
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="text-white nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{user.username}} 님
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item " href="{% url 'articles:mypage' user.id %}">마이페이지</a>
                <a class="dropdown-item" href="{% url 'accounts:update' %}">정보수정</a>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
              </div>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="text-white nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            <li class="nav-item">
              <a class="text-white nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

  <!-- {% block aside %}
  {% endblock %} -->
  <div id="content" class="container my-4">
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/ceef7cd6de.js" crossorigin="anonymous"></script>
</body>
</html>