accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/mypage/', views.mypage, name='mypage'),

    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/comment/create', views.comment_create, name='comment_create'),
    path('<int:article_id>/comment/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),

    path('search/', views.search, name='search'),
    path('<int:id>/like/', views.like, name='like'),
]

dcinside/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.processors import ResizeToFill
from imagekit.models import ProcessedImageField


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = ProcessedImageField(
                null=True, # 필드값 유효성검사할 때 빈값도 가능
                blank=True, # 모델폼 입력할 때 빈값도 가능
                processors=[ResizeToFill(300,300)], # 비율이 안깨지게(리스트형태)
                format='JPEG',
                options={'quality':90}, # 생략해도 상관없음
                upload_to='articles' # 경로
            )
    info = models.BooleanField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    views = models.IntegerField(default=0)
    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    image = ProcessedImageField(
                null=True, # 필드값 유효성검사할 때 빈값도 가능
                blank=True, # 모델폼 입력할 때 빈값도 가능
                processors=[ResizeToFill(100,100)], # 비율이 안깨지게(리스트형태)
                format='JPEG',
                options={'quality':90}, # 생략해도 상관없음
                upload_to='articles' # 경로
            )

# class Like(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
#     article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('info', 'title', 'content', 'image',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content','image',)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm, CommentForm
from .models import Article, Comment
from IPython import embed
# from django.db.models import Q
from django.db.models import Count
from django.contrib.auth import get_user_model

# Create your views here.
def index(request):
    like = False
    view = False
    time = False
    if request.GET.get('likedesc'):
        articles = Article.objects.annotate(like_count=Count('like_users')).order_by('-like_count')
    elif request.GET.get('likeasc'):
        like = True
        articles = Article.objects.annotate(like_count=Count('like_users')).order_by('like_count')
    elif request.GET.get('viewdesc'):
        articles = Article.objects.all().order_by('-views')
    elif request.GET.get('viewasc'):
        view = True
        articles = Article.objects.all().order_by('views')
    elif request.GET.get('timedesc'):
        articles = Article.objects.all().order_by('-created_at')
    elif request.GET.get('timeasc'):
        time = True
        articles = Article.objects.all().order_by('created_at')
    else:
        articles = Article.objects.all()

    context = {
        'articles': articles,
        'like': like,
        'view': view,
        'time': time
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method=='POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            if article.image:
                article.image = request.FILES['image']
            article.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/form.html', context)

def detail(request, id):
    article = get_object_or_404(Article, id=id)
    article_form = ArticleForm(instance=article)
    article = article_form.save(commit=False)
    article.views = article.views + 1
    article.save()
    form = CommentForm()
    # cnt = Like.objects.filter(article=article).count()
    context = {
        'article': article,
        'form': form,
        # 'cnt': cnt,
    }
    return render(request, 'articles/detail.html', context)

def mypage(request, id):
    user = get_object_or_404(get_user_model(), id=id)
    articles = Article.objects.filter(user=user)
    comments = Comment.objects.filter(user=user)
    context = {
        'articles': articles,
        'comments': comments
    }
    return render(request, 'articles/mypage.html', context)

def update(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method=='POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            if request.FILES.get('image'):
                article.image = request.FILES['image']
            article.save()
            return redirect('articles:detail', id)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form
    }
    return render(request, 'articles/form.html', context)

def delete(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    return redirect('articles:index')

def comment_create(request, id):
    if request.method=='POST':
        article = get_object_or_404(Article, id=id)
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.user = request.user
            if request.FILES.get('image'):
                comment.image = request.FILES['image']
            comment.save()
    return redirect('articles:detail', id)

def comment_delete(request, article_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('articles:detail', article_id)

def search(request):
    if request.GET.get('keyword'):
        search_type = 'contains'
        articles = Article.objects.filter(title__contains=request.GET.get('keyword')).order_by('-created_at')
        articles2 = Article.objects.filter(content__contains=request.GET.get('keyword')).order_by('-created_at')
        return render(request, 'articles/search.html', {'articles': articles, 'articles2': articles2})
    else:
        return redirect('articles:index')

def like(request, id):
    article = get_object_or_404(Article, id=id)
    user = request.user
    if article.like_users.filter(id=user.id):
        article.like_users.remove(user)
    else:
        article.like_users.add(user)
    # if Like.objects.filter(article=article, user=user):
    #     like = get_object_or_404(Like, user=request.user)
    #     like.delete()
    # else:
    #     like = Like()
    #     like.user = request.user
    #     like.article = article
    #     like.save()
    return redirect('articles:detail', id)

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h3 id="name"><a href="{% url 'articles:index' %}" style="color:#4a57a8; text-decoration: None;">기본  갤러리</a></h3>
  <div class="card mt-3">
    <div class="card-body">
      <h4 class="card-title">{{article.title}}</h4>
      <div class="d-flex justify-content-between">
        <h6 class="card-subtitle text-muted">작성자 {{article.user}}</h6>
        <h6 class="card-subtitle text-muted text-right">{{article.created_at|date:'Y.m.d H:m:s'}}</h6>
      </div>
      <hr style="border: 1.5px solid gray" class="mb-5">
      <p class="card-text">{{article.content}}</p>
      {% if article.image %}
        <img src="{{article.image.url}}" alt="">
      {% endif %}

      <div class="text-center">
        {% if user.is_authenticated %}
          <a class="btn btn-primary" href="{% url 'articles:like' article.id %}">좋아요 <i class="far fa-thumbs-up"></i> {{article.like_users.count}}</a>
        {% else %}
          <a class="btn btn-primary" href="#" onclick="alert('로그인 후 사용가능합니다.')">좋아요 <i class="far fa-thumbs-up"></i> {{article.like_users.count}}</a>
        {% endif %}
      </div>

      <div class="text-right mt-5">
        <a href="{% url 'articles:index' %}" class="card-link" style="color:#4a57a8;">목록</a>
        <!-- 작성자만 수정/삭제가 가능하다. -->
        {% if request.user == article.user %}
          <a href="{% url 'articles:update' article.id %}" class="card-link" style="color:#4a57a8;">수정</a>
          <a href="{% url 'articles:delete' article.id %}" class="card-link" style="color:#4a57a8;">삭제</a>
        {% endif %}
      </div>
    </div>
  </div>

  {% if user.is_authenticated %}
    <form action="{% url 'articles:comment_create' article.id %}" class="mt-3 alert alert-secondary" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_field form.content show_label=False placeholder='댓글을 입력해주세요.' %}
      {% bootstrap_field form.image show_label=False %}
      <div class="text-right">
        <input class="btn btn-dark" type="submit" value="등록" >
      </div>
    </form>
  {% else %}
    <div class="mt-3 alert alert-secondary" >
      {% bootstrap_field form.content show_label=False placeholder='로그인 후 작성할 수 있습니다.' %}
      <div class="text-right">
        <input class="btn btn-dark" type="submit" value="등록" >
      </div>
    </div>
  {% endif %}

  <table class="table table-sm">
    <tbody>
      {% for comment in article.comment_set.all %}
      <tr>
        <td><h5><a class="badge badge-pill badge-info" href="{% url 'articles:mypage' comment.user.id %}">{{comment.user}}</a></h5></td>
        <td>
          {% if comment.image %}
          <img src="{{comment.image.url}}" alt="">
          {% endif %}
          &nbsp;{{comment.content}}
        </td>
        <td class="text-right">{{comment.created_at|date:'y.m.d H:m:s'}}</td>
        <td>
          {% if request.user == comment.user or request.user == article.user %}
            <a href="{% url 'articles:comment_delete' article.id comment.id %}">
              <button type="button" class="close" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h1>글쓰기</h1>

  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="my-2">{{ form.info }} 공지</div>
      제목 {% bootstrap_field form.title show_label=False placeholder=False %}
      내용 {% bootstrap_field form.content show_label=False placeholder=False %}
      이미지 {% bootstrap_field form.image show_label=False placeholder=False %}
      <div class="text-right">
        <input class="btn btn-primary" type="submit"> 
      </div>
  </form>
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}
  
<!-- 광고배너공간 -->
<!-- {% block aside %}
  <aside class="m-5">
    <img style="width:300px; height:400px;" src="" alt="">
  </aside>
{% endblock %} -->

{% block body %}
<div class="d-flex justify-content-between">
  <div>
    <h3 id="name" style="color:#4a57a8;">기본 갤러리</h3>
    <!-- <h3 class="btn btn-outline-secondary">공지</h3> -->
  </div>
  {% if user.is_authenticated %}
    <h3><a class="btn btn-outline-secondary" href="{% url 'articles:create' %}"><i class="fas fa-pencil-alt" style="color: #4a57a8;"></i></a></h3>
  {% endif %}
</div>

<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col" class="text-center"><span class="btn">번호</span></th>
      <th></th>
      <th scope="col" class="text-center"><span class="btn">제목</span></th>
      <th scope="col" class="text-center"><span class="btn">작성자</span></th>
      <th>
        <form action="{% url 'articles:index' %}">
          {% if time %}
            <input class="btn" type="submit" name='timedesc' value="▲ 작성시간">
          {% else %}
            <input class="btn" type="submit" name='timeasc' value="▼ 작성시간">
          {% endif %}
        </form>
      </th>
      <th>
        <form action="{% url 'articles:index' %}">
          {% if view %}
            <input class="btn" type="submit" name='viewdesc' value="▲ 조회수">
          {% else %}
            <input class="btn" type="submit" name='viewasc' value="▼ 조회수">
          {% endif %}
        </form>
      </th>
      <th class="text-center" scope="col">
        <form action="{% url 'articles:index' %}">
          {% if like %}
            <input class="btn" type="submit" name='likedesc' value="▲ 추천수">
          {% else %}
            <input class="btn" type="submit" name='likeasc' value="▼ 추천수">
          {% endif %}
        </form>
      </th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
      {% if article.info %}
        <tr>
          <td class="text-center" width="7%">공지</td>
          <td width="3%"><i class="fas fa-info-circle" style="color:#82EB5A;"></i></td>
          <td width="40%"><a href="{% url 'articles:detail' article.pk %}">{{article.title}} [{{article.comment_set.count}}]</a></td>
          <td class="text-center" width="10%">{{article.user}}</td>
          <td class="text-center" width="14%">{{article.created_at|date:'y.m.d H:m:s'}}</td>
          <td class="text-center" width="8%">{{article.views}}</td>
          <td class="text-center" width="8%">{{article.like_users.count}}</td>
        </tr>
      {% endif %}
    {% endfor %}
  </tbody>
  <tbody>
    {% for article in articles %}
      {% if not article.info %}
        <tr>
          <td class="text-center" width="7%">{{article.id}}</td>
          <td>
            {% if article.image %}
              <i class="fas fa-images" style="color:#FFDC3C;"></i>
            {% else %}
              <i class="fas fa-comment-dots" style="color:#696969;"></i>
            {% endif %}
          </td>
          <td width="40%"><a href="{% url 'articles:detail' article.pk %}">{{article.title}} [{{article.comment_set.count}}]</a></td>
          <td class="text-center" width="10%" class="text-right">{{article.user}}</td>
          <td class="text-center" width="14%" class="text-right">{{article.created_at|date:'y.m.d H:m:s'}}</td>
          <td class="text-center" width="8%">{{article.views}}</td>
          <td class="text-center" width="8%">{{article.like_users.count}}</td>
        </tr>
        </tr>
      {% endif %}
    {% endfor %}
  </tbody>
</table>
{% endblock %}

articles/templates/articles/mypage.html
{% extends 'base.html' %}
{% block body %}

  <h4>내가 쓴 글</h4>
  <table class="table table-sm">
    <thead>
      <tr>
        <th class="text-center">글번호</th>
        <th class="text-center" scope="col">제목</th>
        <th class="text-center" scope="col" class="text-right">작성시간</th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
      <tr>
        <td width="5%" class="text-center">{{article.id}}</td>
        <td width="20%" class="text-center"><a href="{% url 'articles:detail' article.id %}">{{article.title}}</a></td>
        <td width="20%" class="text-center">{{article.created_at|date:'y.m.d H:m:s'}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <h4 class="mt-5">내가 쓴 댓글</h4>
  <table class="table table-sm">
      <thead>
        <tr>
          <th class="text-center" >글번호</th>
          <th class="text-center" scope="col">내용</th>
          <th class="text-center" scope="col" class="text-right">작성시간</th>
        </tr>
      </thead>
      <tbody>
        {% for comment in comments %}
        <tr>
          <td width="5%" class="text-center">{{comment.article.id}}</td>
          <td class="text-center" width="20%"><a href="{% url 'articles:detail' comment.article.id %}">{{ comment.content }}</a></td>
          <td class="text-center" width="20%" class="text-right">{{comment.created_at|date:'y.m.d H:m:s'}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="text-right my-5">
      <a href="{% url 'accounts:delete' user.id %}" onclick="return confirm('정말 탈퇴하시겠습니까?');">회원탈퇴</a>
    </div>
{% endblock %}

articles/templates/articles/search.html
{% extends 'base.html' %}
{% block body %}

  <h4 class="mb-4">제목 검색결과</h4>
  <div class="mx-3">
    {% for article in articles %}
      <h5><a href="{% url 'articles:detail' article.id %}">{{article.title}}</a></h5>
      {{article.user}} &nbsp;|&nbsp; {{article.created_at|date:'y.m.d H:m:s'}}
    {% endfor %}
  </div>

  <hr class="my-5">
  <h4 class="mb-4">내용 검색결과</h4>
  <div class="mx-3">
    {% for article in articles2 %}
      <h5><a href="{% url 'articles:detail' article.id %}">{{article.title}}</a></h5>
      {{article.user}} &nbsp;|&nbsp; {{article.created_at|date:'y.m.d H:m:s'}}
    {% endfor %}
  </div>
{% endblock %}